project:
  type: book

book:
  chapters:
    - index.qmd
    - Presentation du master SEP.qmd
    - Administration publique.qmd
    - Aeronotique, Espace, defense et securite.qmd
    - Banque et Assurance.qmd
    - Commerce et Industrie.qmd
    - Conseil.qmd
    - Economie et developpement.qmd
    - Edition de logiciels.qmd
    - Energie.qmd
    - Grande distribution.qmd
    - Hotellerie.qmd
    - Informatique et Telecommunication.qmd
    - Luxe.qmd
    - Media.qmd
    - Recherche.qmd
    - Sante.qmd
    - Voyage et tourisme.qmd
    - Autres.qmd


    

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

