---
title: "Hôtellerie"
---

## **HOPTEAM**

Hopteam France est spécialisé dans la vente et l’installation de matériel dans des bars, des hôtels, des restaurants. Le matériel est reparti en 3 catégories : la bière, le café et le CHR (Café Hôtel Restaurant). Le matériel est divers et varié, on retrouve par exemple des colonnes pour tirer de la bière, des groupes froids pour refroidir la bière qui circule dans des tuyaux appelées serpentins, etc...


**Promotion 2023 :**

[Intitulé du stage :]{.underline} 

[Missions(s) :]{.underline} Création d’un formulaire VBA pour ajouter et modifier des demandes
Trouver un modèle pour suivre l’évolution des chiffres d’affaires des
techniciens, et d’avoir des indicateurs de performances, et connaitre pour quel(s) agence(s) ils travaillent.
Des informations sur l’état du stock des produits, ainsi que des consommations
- Calcul d'un potentiel de sanitation pour 2023, et calculer des statistiques sur les becs sanités/CA des sanitations
- Des créations d’articles, extractions de TIP/TB-OMS, création d’accès pour des salariés
- Création d’un fichier sur toutes les commandes fournisseurs de 2019- 2022
- Implémentation automatique des nouveaux tarifs qui sont sous différents formats (pdf, excel, word, etc...)

[Techniques statistiques :]{.underline} 

[Logiciels :]{.underline} SQL/Python/VBA


## **Evian Resort**

Evian Resort est une société active depuis 63 ans dont le siège se trouve à EVIAN-LES-BAINS. Son activité principale est l'hôtellerie et hébergement similaire. Elle appartient à la catégorie des grandes entreprises. Sur l'année 2019 elle réalise un chiffre d'affaires de 64 962 800 euros.

[Lieu du stage :]{.underline} Evian

**Promotion 2019 :**

[Intitulé du stage :]{.underline} Mise en place de l'outil CRM ( Customer Relation Management) et Analyse de délai de réservation de la clientèle hôtel de l'evian resort

[Missions(s) :]{.underline} Mise en place d'un DataLake à partir de données extraites depuis plusieurs SGBD (Un Système de Gestion de Base de Données) et analyse du comportement de réservation de la clientèle pour la mise en place d'un modèle de prédiction des réservations

[Techniques statistiques :]{.underline} Extraction de données, prévision, marketing

[Logiciels :]{.underline} R, Java
