---
title: "Informatique et Télécommunication"
---

## **Big Apps**

BIG APPS est une société de services informatiques. Elle intervient auprès des PME et de grands comptes pour la mise en place de solutions innovantes qui permettent de tirer pleinement profit des solutions et technologies autour de la Big Data, ainsi que de la data science afin d'optimiser le capital immatériel que représentent les données.

[Lieu du stage :]{.underline} Romainville

**Promotion 2018 :**

[Intitulé du stage :]{.underline}

[Missions(s) :]{.underline} Etudier et implémenter un système d'interrogation d'un data lake basé sur le langage humain comme système de requêtage. La restituationde la donnée sera sous forme graphique (machine learning, process NLP).

[Techniques statistiques :]{.underline}

[Logiciels :]{.underline} R

## **Data moove**

Data Moove est une start-up créée en 2014 qui propose une gamme complète de produits technologiques innovants pour le BtoBtoC (business to business to consumer) dans le domaine du tourisme : la plateforme Big Data sémantique City Moove collecte de l'offre touristique à sa diffusion (City Moove) et son exploitation avancée sur tout média digital tel que application mobile, site web, réseaux sociaux ou via l'assistant touristique digital Minotour.

[Lieu du stage :]{.underline} 245 route des Lucioles 06560 Sophia Antipolis, France

**Promotion 2019 :**

[Intitulé du stage :]{.underline} Intelligence artificielle et web sémantique pour l'assistance digitale

[Missions(s) :]{.underline} Ledit stage fait appel à diverses techniques d'intelligence artificielle notamment dans le domaine du web sémantique. Dans le cadre de ce stage, le stagiaire est amené à contribuer à la mise en place d'un système d'assistance automatisé au service de la clientèle (les touristiques) à travers le développement de collecteurs et la construction de nouvelles bases de connaissances. Une base de connaissance, regroupe un ensemble connaissances spécifiques à un domaine spécialisé donné , sous une forme exploitable par un ordinateur. Ces données (connaissances) proviennent de sources variées et sont récupérées grâce à des collecteurs.

[Techniques statistiques :]{.underline} web sémantique, base de connaissance, machine learning, deep learning. Le web sémantique encore appelé le web de données permet aux machines de comprendre la sémantique, la signification de l'information sur le web. Il fournit un modèle qui permet aux données d'être partagées et réutilisées entre plusieurs applications, entreprises et groupes d'utilisateurs.

[Logiciels :]{.underline} Python, RASA, JAVA. RASA est une plateforme qui permet aux développeurs de créer, d'améliorer et de déployer de meilleurs assistants (Intelligence artificielle) alimentés par une source ouverte.

## **Line Up Data Science**

LINEUP DATA SCIENCE est une startup française créée en 2016 à Paris. Elle se spécialise dans le secteur d'activité du traitement de données, hébergement et activités connexes. Elle emploie 90 salariés. Elle a réalisé un chiffre d'affaires de 5685215 d'euros en 2018. Elle se situe dans la catégorie des petites et moyennes entreprises (PME).

[Lieu du stage :]{.underline} 7 rue de Caumartin 75009 PARIS

**Promotion 2020 :**

[Intitulé du stage :]{.underline} Data Science orienté Marketing

[Missions(s) :]{.underline}

-   Cadrage du besoin avec le client (cas d'usage associé, période observée, pilotes envisagés, apprentissages attendus : théorie, programmation, outils, méthodologie Data Science, etc.)

-   Etat de l'art et mise en évidence de méthodes adaptées aux problématiques

-   Analyse des outils, langages les plus pertinents pour mettre en œuvre les modélisations à construire

[Techniques statistiques :]{.underline}

[Logiciels :]{.underline} AWS, Dataiku,GCP, Python, SQL

## **Linkfluence FRANCE**

Linkfluence est une startup française spécialisée dans l'écoute et l'analyse du web social créée en 2006. Elle est rachetée en 2021 par l'entreprise américaine Meltwater.

[Lieu du stage :]{.underline} 5 Rue choron 75009 Paris

**Promotion 2020 :**

[Intitulé du stage :]{.underline} Science des données appliquée en environnement "big data"

[Missions(s) :]{.underline} analyser les données sociales, explorer les nouveaux algorithmes de machine learning, construire des visualisations, fournir une expertise aux equipes de vente, de marketing et de R&D

[Techniques statistiques :]{.underline} Regression, NLP, clustering, series temporelles

[Logiciels :]{.underline} Radarly, Python, Pyspark

## **Monstock**

Monstock est une société qui fournit des solutions de gestion de stocks créée en 2018 à Reims. Elle est spécialisée dans le secteur d'activité de la programmation informatique. Son effectif est entre 3 à 5 salariés. Son capital social est évalué à 13570 euros. Elle appartient à la catégorie petite et moyenne entreprise (PME).

[Lieu du stage :]{.underline} 17 Rond-point de l'Europe, 51430 Bezannes

**Promotion 2020 :**

[Intitulé du stage :]{.underline}

[Missions(s) :]{.underline}

-   Participer à construire des scores prédictifs (performances supply chain, stockage, picking,... etc)

-   Segmentation clustering pour mise en place d'une approche type Magic Quadrant gartner

-   Mettre en place une procédure de qualification de la data

-   Dashboarding & data visualization via une plateforme type Looker

-   Structuration des tables big query, documentation, conception de dictionnaire de donnée

-   Mettre en place l'industrialisation des dashboarding avec une plateforme type Qlik sense

-   Suivre le pilotage du pipeline data associé

[Techniques statistiques :]{.underline} Gestion de projet, Data qualification, Data visualization

[Logiciels :]{.underline} R, SQL, Python, AWS Aurora, DynamoDB, Redshift DB React, Python, Apache, Jupyter, Gitlab S3

## **Mybestpro (telecommunications)**

Mybestpro est une entreprise active depuis 16 ans évoluant dans le secteur d'activité du conseil en systèmes et logiciels informatiques dont le siège social se trouve à PARIS. L'entreprise emploie entre 100 à 199 salariés, elle appartient à la catégorie de petite et moyenne entreprise. Son chiffre d'affaires sur l'année 2019 s'élève à hauteur de 16 399 500 euros.

[Lieu du stage :]{.underline} Paris

**Promotion 2018 :**

[Intitulé du stage :]{.underline}

[Missions(s) :]{.underline} Algo pour système de recommandation, text mining avec prédiction de taux d'acceptation (sur document de type devis), analyse d'impact.

[Techniques statistiques :]{.underline}

[Logiciels :]{.underline} R

## **Orange SA**

Orange Business Services (OBS) est une entité du groupe Orange, elle fournit des services informatiques et de télécommunications dans le monde, à destination des clients professionnels. C'est une entité commerciale que le groupe a constitué le 1er juin 2006. Elle est présente dans 220 pays et territoires et propose des services de connectivité aux entreprises. En quelques chiffres, OBS offre ses solutions informatiques à plus de 2 000 000 de clients professionnels PME dans le monde, plus de 100 000 client Cloud Pro et plus de 3 000 multinationales. Pour assurer le bon fonctionnement des solutions proposées ainsi que l'accompagnement client. L'entreprise a embauché plus de 21 000 collaborateurs dédiés aux activités entreprises. C'est grâce à cela que l'entreprise assure un chiffre d'affaires de 6,4 milliards d'euros en 2016.

**Promotion 2022 :**

[Lieu du stage :]{.underline}

[Intitulé du stage :]{.underline} Stage en tant que Data Analyst

[Missions(s) :]{.underline} Projet R3l2 regroupant les ventes des reconditionnés, des reprises, des recyclés, du leasing et des locations. Chargée des locations et de l'uniformisation des différents suivis: - Recréer le datamart des locations -Réaliser le dashboard de suivi des locations. -Mettre le suivi du leasing avec le dashboard de location en suivant le même format - Ajouter à ce dashboard un onglet de suivi global regroupant à la fois les locations et le leasing. Projet SIMplissime concernant le suivi des eSIM: -Créer un référentiel des cartes SIM permettant d'avoir le maximum d'informations sur celle-ci. - Réaliser un dashboard basé sur des diapositives PowerPoint réalisées par le métier. Projet initié par la stagiaire: Création d'un glossaire commun à toute l'équipe et à tous les dashboards. Participer aux tâches hebdomadaires de l'équipe concernant l'alimentation des datamarts SAS et des sources de données Dataviz.

[Techniques statistiques :]{.underline} Analyse des données

[Logiciels :]{.underline} SAS Base/ Tableau/ Jira/ Confluence

**Promotion 2021 :**

[Lieu du stage :]{.underline} 94110 ARCUEIL

[Intitulé du stage :]{.underline} Data Science

[Missions(s) :]{.underline} Modélisation de comportements/ Analyse de flux / Reporting / Segmentation / Analyses de durée de vie

[Techniques statistiques :]{.underline} Automatisation des données / Modélisation / Machine learning/ Data visualisation

[Logiciels :]{.underline} Dataiku, SAS, SQL, Python, R ou de SPSS.

**Promotion 2018 :**

[Lieu du stage :]{.underline} 78 rue Olivier de Serres Paris

[Intitulé du stage :]{.underline} Analyse de données marketing (vente, achat, stock, prévision de ventes) des pays Orange (zone Europe et Middle-East/Afrique)

[Missions(s) :]{.underline}

-   Analyse de données marketing (vente, achat, stock, prévision de ventes) des pays Orange (zone Europe et Middle-east/Afrique) : def et fiabilisation du processus de récupération de données (format MS ACCESS), mise en place requetes SQL d'intégration, analyse avec les utilisateurs cibles. Mise en place des requêtes SQL d'analyse (avec VBA + ThinkCell), propositions d'axes d'analyses marketing.

-   Analyse des sources alternatives de données (réseaux sociaux, usages applicatifs etc).

[Techniques statistiques :]{.underline}

[Logiciels :]{.underline} Access, SQL, VBA, R

**Promotion 2017 :**

[Lieu du stage :]{.underline} 12F Rue du Patis Tatelin, 35700 Rennes

[Intitulé du stage :]{.underline} Analyse de données d'usage client

[Missions(s) :]{.underline}

-   Définir avec le responsable de stage les cas d'études à analyser (par exemple :

-   catégorisation clients, évolution du panier moyen, types de comportements d'usages) /Identifier les sources de données exploitables pour traiter ces cas (fichiers de logs des portails et équipements, entre autres)

-   Identifier et déployer des outils propres à explorer, analyser, et traiter ces données

-   Analyser ces données pour évaluer leur qualité, les éventuels traitements de préparation à leur apporter (complétude, suppression des valeurs aberrantes, etc.), puis identifier les données d'intérêt pour les cas d'études envisagés

-   Identifier, implémenter (ou développer), puis faire tourner des outils d'analyse susceptibles d'apporter des éléments de réponse aux cas d'études identifiés.

[Techniques statistiques :]{.underline} Segmentation, analyse prédictive

[Logiciels :]{.underline} R
