---
title: "Santé"
---

## **Centre Hospitalier de Troyes**

[Lieu de stage :]{.underline} 10003 Troyes

**Promotion 2021 :**

[Intitulé du stage :]{.underline} La gestion des tensions hospitalières par l'intelligence artificielle

[Mission(s) :]{.underline} Se familiariser avec les données hospitalières / Mettre en place un dashboard pour la visualisation de données - Extraire de données utiles (sélection, extraction, nettoyage,etc) / Élaborer un modèle pour la quantification et la modélisation de la tension / Développer un algorithme intelligent pour l'anticipation de la tension / Développer un système d'aide à la décision pour la gestion des épisodes de tension.

[Techniques statistiques :]{.underline} Prédiction / Modélisation / Tableaux de bord

[Logiciels :]{.underline} RStudio / Excel / Power BI

## **Cerner Enviza**

Established in 1979 by Neal Patterson, Paul Gorup, and Cliff Illig, Cerner, an American provider of health information technology (HIT) solutions, devices, and hardware, underwent significant milestones throughout its history.

[Lieu de stage :]{.underline} PARIS 13EME

**Promotion 2023 :**

[Intitulé du stage :]{.underline} Characterization of a Clinical Trial Emulation

[Mission(s) :]{.underline} Proceed with a recently launched internal research project to demonstrate the potential of clinical trial emulation, a method of using real-world data to simulate the results of a clinical trial.

[Techniques statistiques :]{.underline} Nettoyage de données / Analyse des données

[Logiciels :]{.underline} R studio / Excel / SQL / Databricks

## **Cosmetic Dermatology LLC (DR BRANT)**

Frederic Brandt, est un médecin chirurgien spécialisé en dermatologie. Il est considéré comme étant un spécialiste de la peau. Il décide en 1995, de lancer sa marque de cosmétique. Il décide donc de fonder DrBrandt Skincare. Ainsi les produits, qu'il propose sont des produits innovants. En effet, Les produits de la gamme Dr Brandt sont conçus afin de respecter 3 critères importants. Ces critères sont :

-   Les produits sont basés sur la recherche scientifique et dermatologique

-   Les produits sont efficients

-   Les produits sont sans danger pour tous types de peau

Dr Brandt fut l'un des premiers à s'intéresser aux questions relatives au soin de la peau. A titre d'exemple, il fut l'un des premiers à commercialiser des produits pour lutter contre l'acné.

[Lieu de stage :]{.underline} 75008 PARIS

**Promotion 2021 :**

[Intitulé du stage :]{.underline} Data Analyst

[Mission(s) :]{.underline}

-   Conception et mise en place d'une solution de web tracking

-   Collecte des données et analyses

-   Optimisation du site web Shopify pour l'UX et les moteurs de recherche (on-page SEO)

-   Evaluation de l'expérience utilisateur du site et des taux de conversion

-   Mise en place des recommandations SEO.

[Techniques statiques :]{.underline} Webscrapping / Prédiction / Tableaux de bord

[Logiciels utilisés :]{.underline} Salesforces / Shopify

## **KAP CODE**

**Kap Code** est une start-up spécialisée dans le développement de solutions e-santé innovantes à destination des patients atteints de pathologies chroniques.

[Lieu du stage :]{.underline} 28 rue d'Enghein, 75010 Paris

**Promotion 2017 :**

[Intitulé du stage :]{.underline} Détection et analyse de différents types de mesusages de Paracétamol sur des données textuelles provenant des réseaux sociaux dévolus à la santé.

[Missions(s) :]{.underline} L'objectif a été de répondre à une demande de Sanofi (qui est un groupe pharmaceutique et client de Kap code) qui est de pouvoir détecter la présence de trois cas de mésusage des médicaments composés d'au moins du paracétamol. Cette étude permettra à Sonofi d'avoir un suivi dans le temps de l'opinion des patients en amont et en aval de la mesure de prévention sur le surdosage du paracétamol.

[Techniques statistiques :]{.underline} Extraction des données (collecte des données et la mise en forme du dataset), le prétraitement des données (filtrage des données, traitement des valeurs manquantes, dédoublonnage)

[Logiciels :]{.underline} Rstudio, Excel

## **Logever Healthcare**

Logever-Healthcare, lancé en 2008, est l'entité qui est chargé de l'édition, développement et commercialisation de Logicoss. Logicoss a été pensé dans le but de simplifier et rendre fiable les opérations de 8 missions clés, à savoir : - Suivre les patients en poste de secours / - Prendre une alerte au poste de Commande lorsqu'un participant se blesse au cours de l'évènement. / - Engager une équipe de secours pour prendre en charge le patient. • Diriger et superviser les secours. / - Accélérer la remontée d'alerte. / - Fournir des outils de traçabilité aux organisateurs et permettant aussi de protéger de façon juridiques le personnel soignant. / - Informer les autorités en cas de risques majeurs. / - Informer les familles sur l'état et l'emplacement du participant, toujours en course ou transféré dans un hôpital.

[Lieu de stage :]{.underline} 69310 Pierre Benite

**Promotion 2021 :**

[Intitulé du stage :]{.underline} Sport Events

[Mission(s) :]{.underline} Exploitation de la base constituée des données de prises en charge médicales de 500 000 sportifs et de 10 millions de visiteurs de sites tertiaires par an. / Poursuivre les travaux du modèle prédictif d'accidentologie débuté en 2019. / Fournir les premiers outils d'analyse vers l'optimisation des plannings d'ambulance dans le département du Rhône.

[Techniques statistiques :]{.underline} Analyse de données / tableaux de bord

[Logiciels :]{.underline} RStudio / Python / Gitlab

## **Savane - Data**

SAVANE est une Entreprise de Services du Numérique (ESN) dont le métier est d'apporter une contribution opérationnelle aux projets de transformation digitale de ses clients.

[Lieu du stage :]{.underline}

**Promotion 2023 :**

[Intitulé du stage :]{.underline} Tryptase sérique basale : valeurs de référence dans une étude nationale française de 2022

[Missions(s) :]{.underline} Mission principale était l'étude des diabétiques de type 2 chez Synlab Provence pour classifier les patients en fonction de la dégradation de leur état de santé à cause de la maladie.

[Techniques statistiques :]{.underline} Machine Learning

[Logiciels :]{.underline} SAS/Excel
